/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FlowersIndexRouteImport } from './routes/flowers/index'
import { Route as FlowersAddRouteImport } from './routes/flowers/add'
import { Route as FlowersIdIndexRouteImport } from './routes/flowers/$id/index'
import { Route as FlowersIdEditRouteImport } from './routes/flowers/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowersIndexRoute = FlowersIndexRouteImport.update({
  id: '/flowers/',
  path: '/flowers/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowersAddRoute = FlowersAddRouteImport.update({
  id: '/flowers/add',
  path: '/flowers/add',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowersIdIndexRoute = FlowersIdIndexRouteImport.update({
  id: '/flowers/$id/',
  path: '/flowers/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowersIdEditRoute = FlowersIdEditRouteImport.update({
  id: '/flowers/$id/edit',
  path: '/flowers/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flowers/add': typeof FlowersAddRoute
  '/flowers': typeof FlowersIndexRoute
  '/flowers/$id/edit': typeof FlowersIdEditRoute
  '/flowers/$id': typeof FlowersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flowers/add': typeof FlowersAddRoute
  '/flowers': typeof FlowersIndexRoute
  '/flowers/$id/edit': typeof FlowersIdEditRoute
  '/flowers/$id': typeof FlowersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flowers/add': typeof FlowersAddRoute
  '/flowers/': typeof FlowersIndexRoute
  '/flowers/$id/edit': typeof FlowersIdEditRoute
  '/flowers/$id/': typeof FlowersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/flowers/add'
    | '/flowers'
    | '/flowers/$id/edit'
    | '/flowers/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/flowers/add' | '/flowers' | '/flowers/$id/edit' | '/flowers/$id'
  id:
    | '__root__'
    | '/'
    | '/flowers/add'
    | '/flowers/'
    | '/flowers/$id/edit'
    | '/flowers/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlowersAddRoute: typeof FlowersAddRoute
  FlowersIndexRoute: typeof FlowersIndexRoute
  FlowersIdEditRoute: typeof FlowersIdEditRoute
  FlowersIdIndexRoute: typeof FlowersIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flowers/': {
      id: '/flowers/'
      path: '/flowers'
      fullPath: '/flowers'
      preLoaderRoute: typeof FlowersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flowers/add': {
      id: '/flowers/add'
      path: '/flowers/add'
      fullPath: '/flowers/add'
      preLoaderRoute: typeof FlowersAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flowers/$id/': {
      id: '/flowers/$id/'
      path: '/flowers/$id'
      fullPath: '/flowers/$id'
      preLoaderRoute: typeof FlowersIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flowers/$id/edit': {
      id: '/flowers/$id/edit'
      path: '/flowers/$id/edit'
      fullPath: '/flowers/$id/edit'
      preLoaderRoute: typeof FlowersIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlowersAddRoute: FlowersAddRoute,
  FlowersIndexRoute: FlowersIndexRoute,
  FlowersIdEditRoute: FlowersIdEditRoute,
  FlowersIdIndexRoute: FlowersIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
